// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"kratos-demo/app/demo/internal/biz"
	"kratos-demo/app/demo/internal/conf"
	"kratos-demo/app/demo/internal/data"
	"kratos-demo/app/demo/internal/server"
	"kratos-demo/app/demo/internal/service"
	"kratos-demo/pkg/nacos"
	conf2 "kratos-demo/pkg/nacos/conf"
)

import (
	_ "github.com/go-kratos/kratos/v2/encoding/yaml"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, confNacos *conf2.Nacos, jwt *conf.Jwt, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData, logger)
	client := data.NewRedis(confData, logger)
	dataData, cleanup, err := data.NewData(db, client, logger)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	userUseCase := biz.NewUserUseCase(userRepo, logger)
	userService := service.NewUserService(userUseCase, logger)
	grpcServer := server.NewGRPCServer(confServer, userService, logger)
	loginUseCase := biz.NewLoginUseCase(userRepo, logger, jwt)
	loginService := service.NewLoginService(loginUseCase, logger)
	httpServer := server.NewHTTPServer(confServer, userService, loginService, jwt, client, logger)
	registrar := nacos.NewRegistrar(confNacos)
	app := newApp(logger, grpcServer, httpServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
