// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.4
// source: conf/nacos.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NacosBootstrap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nacos *Nacos `protobuf:"bytes,1,opt,name=nacos,proto3" json:"nacos,omitempty"`
}

func (x *NacosBootstrap) Reset() {
	*x = NacosBootstrap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_conf_nacos_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NacosBootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NacosBootstrap) ProtoMessage() {}

func (x *NacosBootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_conf_nacos_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NacosBootstrap.ProtoReflect.Descriptor instead.
func (*NacosBootstrap) Descriptor() ([]byte, []int) {
	return file_conf_nacos_proto_rawDescGZIP(), []int{0}
}

func (x *NacosBootstrap) GetNacos() *Nacos {
	if x != nil {
		return x.Nacos
	}
	return nil
}

type Nacos struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Discovery *Nacos_Discovery `protobuf:"bytes,1,opt,name=discovery,proto3" json:"discovery,omitempty"`
	Config    *Nacos_Config    `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *Nacos) Reset() {
	*x = Nacos{}
	if protoimpl.UnsafeEnabled {
		mi := &file_conf_nacos_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Nacos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nacos) ProtoMessage() {}

func (x *Nacos) ProtoReflect() protoreflect.Message {
	mi := &file_conf_nacos_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nacos.ProtoReflect.Descriptor instead.
func (*Nacos) Descriptor() ([]byte, []int) {
	return file_conf_nacos_proto_rawDescGZIP(), []int{1}
}

func (x *Nacos) GetDiscovery() *Nacos_Discovery {
	if x != nil {
		return x.Discovery
	}
	return nil
}

func (x *Nacos) GetConfig() *Nacos_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

type Nacos_Discovery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip                  string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                uint64 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	NamespaceId         string `protobuf:"bytes,3,opt,name=NamespaceId,proto3" json:"NamespaceId,omitempty"`
	Group               string `protobuf:"bytes,4,opt,name=Group,proto3" json:"Group,omitempty"`
	TimeoutMs           uint64 `protobuf:"varint,5,opt,name=TimeoutMs,proto3" json:"TimeoutMs,omitempty"`
	NotLoadCacheAtStart bool   `protobuf:"varint,6,opt,name=NotLoadCacheAtStart,proto3" json:"NotLoadCacheAtStart,omitempty"`
	LogDir              string `protobuf:"bytes,7,opt,name=LogDir,proto3" json:"LogDir,omitempty"`
	CacheDir            string `protobuf:"bytes,8,opt,name=CacheDir,proto3" json:"CacheDir,omitempty"`
	LogLevel            string `protobuf:"bytes,9,opt,name=LogLevel,proto3" json:"LogLevel,omitempty"`
}

func (x *Nacos_Discovery) Reset() {
	*x = Nacos_Discovery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_conf_nacos_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Nacos_Discovery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nacos_Discovery) ProtoMessage() {}

func (x *Nacos_Discovery) ProtoReflect() protoreflect.Message {
	mi := &file_conf_nacos_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nacos_Discovery.ProtoReflect.Descriptor instead.
func (*Nacos_Discovery) Descriptor() ([]byte, []int) {
	return file_conf_nacos_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Nacos_Discovery) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Nacos_Discovery) GetPort() uint64 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Nacos_Discovery) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *Nacos_Discovery) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *Nacos_Discovery) GetTimeoutMs() uint64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *Nacos_Discovery) GetNotLoadCacheAtStart() bool {
	if x != nil {
		return x.NotLoadCacheAtStart
	}
	return false
}

func (x *Nacos_Discovery) GetLogDir() string {
	if x != nil {
		return x.LogDir
	}
	return ""
}

func (x *Nacos_Discovery) GetCacheDir() string {
	if x != nil {
		return x.CacheDir
	}
	return ""
}

func (x *Nacos_Discovery) GetLogLevel() string {
	if x != nil {
		return x.LogLevel
	}
	return ""
}

type Nacos_Config struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip                  string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                uint64 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	NamespaceId         string `protobuf:"bytes,3,opt,name=NamespaceId,proto3" json:"NamespaceId,omitempty"`
	Group               string `protobuf:"bytes,4,opt,name=Group,proto3" json:"Group,omitempty"`
	TimeoutMs           uint64 `protobuf:"varint,5,opt,name=TimeoutMs,proto3" json:"TimeoutMs,omitempty"`
	NotLoadCacheAtStart bool   `protobuf:"varint,6,opt,name=NotLoadCacheAtStart,proto3" json:"NotLoadCacheAtStart,omitempty"`
	LogDir              string `protobuf:"bytes,7,opt,name=LogDir,proto3" json:"LogDir,omitempty"`
	CacheDir            string `protobuf:"bytes,8,opt,name=CacheDir,proto3" json:"CacheDir,omitempty"`
	LogLevel            string `protobuf:"bytes,9,opt,name=LogLevel,proto3" json:"LogLevel,omitempty"`
	DataId              string `protobuf:"bytes,10,opt,name=DataId,proto3" json:"DataId,omitempty"`
}

func (x *Nacos_Config) Reset() {
	*x = Nacos_Config{}
	if protoimpl.UnsafeEnabled {
		mi := &file_conf_nacos_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Nacos_Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nacos_Config) ProtoMessage() {}

func (x *Nacos_Config) ProtoReflect() protoreflect.Message {
	mi := &file_conf_nacos_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nacos_Config.ProtoReflect.Descriptor instead.
func (*Nacos_Config) Descriptor() ([]byte, []int) {
	return file_conf_nacos_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Nacos_Config) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Nacos_Config) GetPort() uint64 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Nacos_Config) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *Nacos_Config) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *Nacos_Config) GetTimeoutMs() uint64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *Nacos_Config) GetNotLoadCacheAtStart() bool {
	if x != nil {
		return x.NotLoadCacheAtStart
	}
	return false
}

func (x *Nacos_Config) GetLogDir() string {
	if x != nil {
		return x.LogDir
	}
	return ""
}

func (x *Nacos_Config) GetCacheDir() string {
	if x != nil {
		return x.CacheDir
	}
	return ""
}

func (x *Nacos_Config) GetLogLevel() string {
	if x != nil {
		return x.LogLevel
	}
	return ""
}

func (x *Nacos_Config) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

var File_conf_nacos_proto protoreflect.FileDescriptor

var file_conf_nacos_proto_rawDesc = []byte{
	0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x66, 0x2f, 0x6e, 0x61, 0x63, 0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x1a, 0x1e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x39,
	0x0a, 0x0e, 0x4e, 0x61, 0x63, 0x6f, 0x73, 0x42, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70,
	0x12, 0x27, 0x0a, 0x05, 0x6e, 0x61, 0x63, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4e, 0x61, 0x63,
	0x6f, 0x73, 0x52, 0x05, 0x6e, 0x61, 0x63, 0x6f, 0x73, 0x22, 0x9d, 0x05, 0x0a, 0x05, 0x4e, 0x61,
	0x63, 0x6f, 0x73, 0x12, 0x39, 0x0a, 0x09, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x4e, 0x61, 0x63, 0x6f, 0x73, 0x2e, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76,
	0x65, 0x72, 0x79, 0x52, 0x09, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x12, 0x30,
	0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4e, 0x61, 0x63, 0x6f,
	0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x1a, 0x87, 0x02, 0x0a, 0x09, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x70, 0x6f,
	0x72, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x69,
	0x6d, 0x65, 0x6f, 0x75, 0x74, 0x4d, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x54,
	0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x4d, 0x73, 0x12, 0x30, 0x0a, 0x13, 0x4e, 0x6f, 0x74, 0x4c,
	0x6f, 0x61, 0x64, 0x43, 0x61, 0x63, 0x68, 0x65, 0x41, 0x74, 0x53, 0x74, 0x61, 0x72, 0x74, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x13, 0x4e, 0x6f, 0x74, 0x4c, 0x6f, 0x61, 0x64, 0x43, 0x61,
	0x63, 0x68, 0x65, 0x41, 0x74, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x4c, 0x6f,
	0x67, 0x44, 0x69, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4c, 0x6f, 0x67, 0x44,
	0x69, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x61, 0x63, 0x68, 0x65, 0x44, 0x69, 0x72, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x61, 0x63, 0x68, 0x65, 0x44, 0x69, 0x72, 0x12, 0x1a,
	0x0a, 0x08, 0x4c, 0x6f, 0x67, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x4c, 0x6f, 0x67, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x1a, 0x9c, 0x02, 0x0a, 0x06, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x4e, 0x61, 0x6d,
	0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x4d, 0x73, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x4d, 0x73, 0x12,
	0x30, 0x0a, 0x13, 0x4e, 0x6f, 0x74, 0x4c, 0x6f, 0x61, 0x64, 0x43, 0x61, 0x63, 0x68, 0x65, 0x41,
	0x74, 0x53, 0x74, 0x61, 0x72, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x13, 0x4e, 0x6f,
	0x74, 0x4c, 0x6f, 0x61, 0x64, 0x43, 0x61, 0x63, 0x68, 0x65, 0x41, 0x74, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x4c, 0x6f, 0x67, 0x44, 0x69, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x4c, 0x6f, 0x67, 0x44, 0x69, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x61, 0x63,
	0x68, 0x65, 0x44, 0x69, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x61, 0x63,
	0x68, 0x65, 0x44, 0x69, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x6f, 0x67, 0x4c, 0x65, 0x76, 0x65,
	0x6c, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4c, 0x6f, 0x67, 0x4c, 0x65, 0x76, 0x65,
	0x6c, 0x12, 0x16, 0x0a, 0x06, 0x44, 0x61, 0x74, 0x61, 0x49, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x44, 0x61, 0x74, 0x61, 0x49, 0x64, 0x42, 0x29, 0x5a, 0x27, 0x6b, 0x72, 0x61,
	0x74, 0x6f, 0x73, 0x2d, 0x64, 0x65, 0x6d, 0x6f, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x75, 0x73, 0x65,
	0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x3b,
	0x63, 0x6f, 0x6e, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_conf_nacos_proto_rawDescOnce sync.Once
	file_conf_nacos_proto_rawDescData = file_conf_nacos_proto_rawDesc
)

func file_conf_nacos_proto_rawDescGZIP() []byte {
	file_conf_nacos_proto_rawDescOnce.Do(func() {
		file_conf_nacos_proto_rawDescData = protoimpl.X.CompressGZIP(file_conf_nacos_proto_rawDescData)
	})
	return file_conf_nacos_proto_rawDescData
}

var file_conf_nacos_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_conf_nacos_proto_goTypes = []interface{}{
	(*NacosBootstrap)(nil),  // 0: kratos.api.NacosBootstrap
	(*Nacos)(nil),           // 1: kratos.api.Nacos
	(*Nacos_Discovery)(nil), // 2: kratos.api.Nacos.Discovery
	(*Nacos_Config)(nil),    // 3: kratos.api.Nacos.Config
}
var file_conf_nacos_proto_depIdxs = []int32{
	1, // 0: kratos.api.NacosBootstrap.nacos:type_name -> kratos.api.Nacos
	2, // 1: kratos.api.Nacos.discovery:type_name -> kratos.api.Nacos.Discovery
	3, // 2: kratos.api.Nacos.config:type_name -> kratos.api.Nacos.Config
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_conf_nacos_proto_init() }
func file_conf_nacos_proto_init() {
	if File_conf_nacos_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_conf_nacos_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NacosBootstrap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_conf_nacos_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Nacos); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_conf_nacos_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Nacos_Discovery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_conf_nacos_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Nacos_Config); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_conf_nacos_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_conf_nacos_proto_goTypes,
		DependencyIndexes: file_conf_nacos_proto_depIdxs,
		MessageInfos:      file_conf_nacos_proto_msgTypes,
	}.Build()
	File_conf_nacos_proto = out.File
	file_conf_nacos_proto_rawDesc = nil
	file_conf_nacos_proto_goTypes = nil
	file_conf_nacos_proto_depIdxs = nil
}
